### ISSUE TITLE
Failed. same routing pattern.

### ISSUE THREAD

**Issue by UYEONG** [WebFrontEnd/jindo.router#14]
### Failed CASE
```javascript
var fnListener1 = sinon.spy(),
    fnListener2 = sinon.spy();

jindo.router.register('/my/friends/:friend', fnListener1);
jindo.router.register('/my/friends/:id', fnListener2);

jindo.router.navigate('/my/friends/1111');

assert.ok(fnListener1.calledOnce);
assert.ok(fnListener1.calledWith({friend : '1111'}));

assert.ok(fnListener2.calledOnce);
assert.ok(fnListener2.calledWith({id : '1111'}));
```

**Comment by Jinkwon** [comment]
Data should be return mapping property name.

- Examples
jindo.router.on(‘/my/friends/:id’, function(obj){// return { id : 123} });
jindo.router.on(‘/my/friends/:friend’, funciton(obj){ // return {friend : 123});
jindo.router.navigate(‘/my/friends/123’);

**Comment by UYEONG** [comment]
@Jinkwon Check PLZ.

**Comment by Jinkwon** [comment]
@UYEONG I leaved commend to UYOUNG@994ba12e7fb74a9e1764493635dd2cc1183f3942

**Comment by UYEONG** [comment]
코멘트 달아주신 테스트 코드에서도 정상적으로 동작함을 확인 했습니다~! 이 이슈는 닫겠습니다.
