### ISSUE TITLE
라우터 관리 기능 개발

### ISSUE THREAD

**Issue by UYEONG** [WebFrontEnd/jindo.router#2]
### 유스케이스 1. 사용자는 라우터를 생성할 수 있다.
* 사용자는 라우터를 생성할 수 있다.
* 사용자는 숫자 형식의 세그먼트를 지원하는 라우터를 생성할 수 있다.
  * /my/friends/:friend => /my/friends/166546
  * /my/friends/:friend/jobs/:job => /my/friends/166546/jobs/12

### 유스케이스 2. 사용자는 특정 라우터에 리스너를 등록할 수 있다.
* 사용자는 라우터와 리스너를 생성하고 등록할 수 있다.
* 사용자는 이미 생성된 라우터에 리스너를 등록할 수 있다.

### 유스케이스 3. 사용자는 라우터를 제거할 수 있다.
* 사용자는 특정 라우터를 제거할 수 있다.

### 유스케이스 4. 사용자는 특정 라우터의 리스너를 해제할 수 있다.
* 사용자는 특정 라우터의 리스너를 해제할 수 있다.

**Comment by Jinkwon** [comment]
유즈케이스 5.
navigate기능을 이용해 강제로 특정 라우터로 이동 시킬수 있다.
이건 어떨까요?

**Comment by UYEONG** [comment]
@Jinkwon 아. 그건 라우팅 기능 개발에 작성하면 좋을 것 같아요. https://github.com/WebFrontEnd/jindo.router/issues/4 에 작성 부탁드립니다 :D
