### ISSUE TITLE
이 라이브러리가 도움이 될런지 모르겠네요. 같이 검토해 보아요~

### ISSUE THREAD

**Issue by Jinkwon** [WebFrontEnd/jindo.router#3]
### URI.js
http://medialize.github.io/URI.js/

**Comment by UYEONG** [comment]
jindo 라이브러리에 router 가 없어서 이번 프로젝트때 직접 진도 클래스 기반으로 라우터를 만들었습니다. 그 소스를 조금 더 고도화해서 개발해 볼까 생각했습니다. (만들어 놨는데 그냥 폐기하기도 아깝고요.) jindo 라이브러리를 사용한다고 할 때 별도의 라우팅 라이브러리를 사용하지 않아도 jindo에서 지원하는 라우팅 라이브러리가 있다면 좋을 것 같았거든요.

**Comment by Jinkwon** [comment]
@UYEONG
최근에 썼던 쓸만하고 가벼운 라이브러리에요.

이 라이브러리를 검토해보자고 한건, 라우팅에서 필수적인 URL파싱을 할 때 도움이 될만한 코드가 있는지, 참고 할만한지 한거에요. (라우팅 라이브러리를 만들지 말자는 의견은 아니구요 ㅋ)
직접 만들면 어디선가 빈틈이 생기니까 다른 라이브러리도 참고하면서 차용해 올 수 있는 코드도 참고하면 어떨까 싶어요.~~

**Comment by UYEONG** [comment]
@Jinkwon 아아. 넵 ㅎㅎ 인터페이스 적인 부분(메서드 명, 세그먼트 지원 방식)만 크로스로드를 참고하고 있었어요. 내부적인 로직은 추천해주신 라이브러리를 한번 살펴보겠습니다.
